package be15fintomatokatchupbe.chat.command.application.service;

import be15fintomatokatchupbe.chat.command.application.dto.request.ChatInviteRequest;
import be15fintomatokatchupbe.chat.command.application.dto.request.CreateChatRoomRequest;
import be15fintomatokatchupbe.chat.command.application.dto.response.CreateChatRoomResponse;
import be15fintomatokatchupbe.chat.command.application.dto.response.ExitChatRoomResponse;
import be15fintomatokatchupbe.chat.command.domain.aggregate.entity.Chat;
import be15fintomatokatchupbe.chat.command.domain.aggregate.entity.UserChat;
import be15fintomatokatchupbe.chat.command.domain.repository.ChatRoomRepository;
import be15fintomatokatchupbe.chat.command.domain.repository.UserChatRepository;
import be15fintomatokatchupbe.chat.exception.ChatErrorCode;
import be15fintomatokatchupbe.chat.query.application.dto.response.UserSimpleDto;
import be15fintomatokatchupbe.common.domain.StatusType;
import be15fintomatokatchupbe.common.exception.BusinessException;
import be15fintomatokatchupbe.user.query.mapper.UserQueryMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.*;

import java.time.LocalDateTime;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class ChatCommandServiceTest {

    @Mock
    private ChatRoomRepository chatRoomRepository;

    @Mock
    private UserChatRepository userChatRepository;

    @Mock
    private UserQueryMapper userQueryMapper;

    @InjectMocks
    private ChatCommandService chatCommandService;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    void createChatRoom_success_withCustomName() {
        CreateChatRoomRequest request = new CreateChatRoomRequest();
        request.setUserId(1L);
        request.setUserIds(Arrays.asList(2L, 3L));
        request.setChatName("우리들의 대화방");

        Chat savedChat = Chat.builder()
                .chatId(100L)
                .chatName("우리들의 대화방")
                .createdAt(LocalDateTime.now())
                .build();

        when(chatRoomRepository.save(any(Chat.class))).thenReturn(savedChat);

        CreateChatRoomResponse response = chatCommandService.createChatRoom(request);

        assertNotNull(response);
        assertEquals(100L, response.getChatId());
        assertEquals("채팅방이 생성되었습니다.", response.getMessage());

        verify(chatRoomRepository, times(1)).save(any(Chat.class));
        verify(userChatRepository, times(3)).save(any(UserChat.class));
    }

    @Test
    void createChatRoom_success_withAutoGeneratedName() {
        CreateChatRoomRequest request = new CreateChatRoomRequest();
        request.setUserId(1L);
        request.setUserIds(Arrays.asList(2L, 3L));
        request.setChatName(null);

        List<UserSimpleDto> userDtos = Arrays.asList(
                new UserSimpleDto(1L, "철수"),
                new UserSimpleDto(2L, "영희"),
                new UserSimpleDto(3L, "민수")
        );
        when(userQueryMapper.findUserNamesByIds(any())).thenReturn(userDtos);

        Chat savedChat = Chat.builder()
                .chatId(200L)
                .chatName("철수, 영희, 민수")
                .createdAt(LocalDateTime.now())
                .build();

        when(chatRoomRepository.save(any(Chat.class))).thenReturn(savedChat);

        CreateChatRoomResponse response = chatCommandService.createChatRoom(request);

        assertEquals(200L, response.getChatId());
        assertEquals("채팅방이 생성되었습니다.", response.getMessage());
    }

    @Test
    void createChatRoom_fail_when_userIds_null() {
        CreateChatRoomRequest request = new CreateChatRoomRequest();
        request.setUserId(1L);
        request.setUserIds(null);

        BusinessException ex = assertThrows(BusinessException.class,
                () -> chatCommandService.createChatRoom(request));

        assertEquals(ChatErrorCode.INVALID_CHAT_ROOM_REQUEST, ex.getErrorCode());
    }

    @Test
    void createChatRoom_fail_when_only_creator() {
        CreateChatRoomRequest request = new CreateChatRoomRequest();
        request.setUserId(1L);
        request.setUserIds(List.of());

        BusinessException ex = assertThrows(BusinessException.class,
                () -> chatCommandService.createChatRoom(request));

        assertEquals(ChatErrorCode.SINGLE_PARTICIPANT_NOT_ALLOWED, ex.getErrorCode());
    }

    @Test
    void exitRoom_success() {
        Long userId = 1L;
        Long chatId = 1L;

        UserChat userChat = UserChat.builder()
                .userChatId(10L)
                .userId(userId)
                .chatId(chatId)
                .isDeleted(StatusType.N)
                .build();

        when(userChatRepository.findByUserIdAndChatIdAndIsDeleted(userId, chatId, StatusType.N))
                .thenReturn(Optional.of(userChat));

        ExitChatRoomResponse response = chatCommandService.exitRoom(userId, chatId);

        assertEquals("채팅방에서 나갔습니다.", response.getMessage());
        assertEquals(StatusType.Y, userChat.getIsDeleted());
        verify(userChatRepository).save(userChat);
    }

    @Test
    void exitRoom_fail_when_userChat_not_found() {
        Long userId = 1L;
        Long chatId = 999L;

        when(userChatRepository.findByUserIdAndChatIdAndIsDeleted(userId, chatId, StatusType.N))
                .thenReturn(Optional.empty());

        BusinessException ex = assertThrows(BusinessException.class,
                () -> chatCommandService.exitRoom(userId, chatId));

        assertEquals(ChatErrorCode.CHAT_ROOM_NOT_FOUND, ex.getErrorCode());
    }

    @Test
    void inviteChatMembers_success_new_and_reinvite() {
        Long chatId = 10L;
        Chat chat = Chat.builder()
                .chatId(chatId)
                .chatName("테스트방")
                .createdAt(LocalDateTime.now())
                .build();

        ChatInviteRequest request = new ChatInviteRequest();
        request.setUserId(1L);
        request.setInvitedUserIds(Arrays.asList(2L, 3L));

        when(chatRoomRepository.findById(chatId)).thenReturn(Optional.of(chat));
        when(userQueryMapper.findUserIdsByIds(any())).thenReturn(Arrays.asList(2L, 3L));
        when(userChatRepository.findByUserIdAndChatId(2L, chatId)).thenReturn(Optional.empty());
        when(userChatRepository.findByUserIdAndChatId(3L, chatId)).thenReturn(Optional.of(
                UserChat.builder()
                        .userId(3L)
                        .chatId(chatId)
                        .isDeleted(StatusType.Y)
                        .build()
        ));

        chatCommandService.inviteChatMembers(chatId, request);

        verify(userChatRepository, times(2)).save(any(UserChat.class));
    }

    @Test
    void inviteChatMembers_fail_when_chat_not_found() {
        Long chatId = 10L;
        ChatInviteRequest request = new ChatInviteRequest();
        request.setUserId(1L);
        request.setInvitedUserIds(List.of(2L));

        when(chatRoomRepository.findById(chatId)).thenReturn(Optional.empty());

        BusinessException ex = assertThrows(BusinessException.class,
                () -> chatCommandService.inviteChatMembers(chatId, request));

        assertEquals(ChatErrorCode.CHAT_ROOM_NOT_FOUND, ex.getErrorCode());
    }

    @Test
    void inviteChatMembers_fail_when_userIds_empty() {
        Long chatId = 10L;
        Chat chat = Chat.builder().chatId(chatId).build();
        ChatInviteRequest request = new ChatInviteRequest();
        request.setUserId(1L);
        request.setInvitedUserIds(List.of());

        when(chatRoomRepository.findById(chatId)).thenReturn(Optional.of(chat));

        BusinessException ex = assertThrows(BusinessException.class,
                () -> chatCommandService.inviteChatMembers(chatId, request));

        assertEquals(ChatErrorCode.INVALID_CHAT_ROOM_REQUEST, ex.getErrorCode());
    }

    @Test
    void inviteChatMembers_fail_when_users_not_found() {
        Long chatId = 10L;
        Chat chat = Chat.builder().chatId(chatId).build();
        ChatInviteRequest request = new ChatInviteRequest();
        request.setUserId(1L);
        request.setInvitedUserIds(List.of(999L));

        when(chatRoomRepository.findById(chatId)).thenReturn(Optional.of(chat));
        when(userQueryMapper.findUserIdsByIds(any())).thenReturn(List.of());

        BusinessException ex = assertThrows(BusinessException.class,
                () -> chatCommandService.inviteChatMembers(chatId, request));

        assertEquals(ChatErrorCode.USER_NOT_FOUND, ex.getErrorCode());
    }
}
